"""added executors and trades

Revision ID: 029ded9296a1
Revises: 87e8ed291604
Create Date: 2023-03-31 19:36:41.067121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029ded9296a1'
down_revision = '87e8ed291604'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
    sa.Column('token', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executors_user_id'), 'executors', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('executor_id', sa.INTEGER(), nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('amount', sa.REAL(), nullable=True),
    sa.Column('executor_amount', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_executor_id'), 'trades', ['executor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_executor_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_executors_user_id'), table_name='executors')
    op.drop_table('executors')
    # ### end Alembic commands ###
