"""added links

Revision ID: 7fe66bcf91cc
Revises: 9110bc1061f3
Create Date: 2023-03-27 15:46:33.197678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe66bcf91cc'
down_revision = '9110bc1061f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quote', sa.VARCHAR(length=15), nullable=True),
    sa.Column('count_new', sa.INTEGER(), nullable=True),
    sa.Column('count_all', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_quote'), 'links', ['quote'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_quote'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
