"""add about and active status for tags

Revision ID: 87e8ed291604
Revises: 7fe66bcf91cc
Create Date: 2023-03-29 12:10:59.439866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e8ed291604'
down_revision = '7fe66bcf91cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('about', sa.TEXT(), nullable=True))
    op.add_column('tags', sa.Column('is_active', sa.BOOLEAN(), nullable=True, server_default="true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'is_active')
    op.drop_column('tags', 'about')
    # ### end Alembic commands ###
