"""added products priority

Revision ID: 9110bc1061f3
Revises: 51fb9257f838
Create Date: 2023-03-06 10:16:22.815978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9110bc1061f3'
down_revision = '51fb9257f838'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('priority', sa.SMALLINT(), nullable=True, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'priority')
    # ### end Alembic commands ###
